### ISSUE TITLE
Pressing enter button on select menu submits the form

### ISSUE THREAD

**Issue by jayantsharma** [jonathantribouharet/jt-rails-address#1]
### Steps to reproduce
- using with [bootstrap_forms gem](https://github.com/bootstrap-ruby/rails-bootstrap-forms)
- search for an address
- press enter on any one of the options
- form submits
#### Expected
- just change the related fields, nothing more

**Comment by johnvuko** [comment]
Sorry but it has nothing to do with my code. Just intercept the event with something like:

```
$('#input').keypress(function (e) {
  if (e.which == 13){
    return false;
  }
});
```

**Comment by jayantsharma** [comment]
Right, thanks!
