### ISSUE TITLE
removing address

### ISSUE THREAD

**Issue by jakehockey10** [jonathantribouharet/jt-rails-address#2]
How would one go about removing an address from an `ActiveRecord` object in the `update` action of that controller?

**Comment by johnvuko** [comment]
I just released a new version (1.3.0) so you could do that, check the README.
There are two ways:
- you add `address_destroy` in your HTML form and if the value is `1` or `true` the address will be remove
- you manually call `my_instance.update(address_destroy: true)`

**Comment by jakehockey10** [comment]
Awesome, thank you so much!
