### ISSUE TITLE
How to migrate address?

### ISSUE THREAD

**Issue by yshmarov** [jonathantribouharet/jt-rails-address#5]
Hello
Migration:
```
class AddAddressToMembers < ActiveRecord::Migration[5.1]
  def change
    add_column :members, :address, :address
  end
end
```
Error:
```
Caused by:
PG::UndefinedObject: ERROR:  type "address" does not exist
LINE 1: ALTER TABLE "members" ADD "address" address
```
and
`undefined method `has_address' for #<Class:0x007f500d44aca0>`

**Comment by johnvuko** [comment]
Hi,
`address` is not a type for postgresql, you can try:

```
class AddAddressToMembers < ActiveRecord::Migration[5.1]
  def change
    change_table :members do |t|
      t.address :address
    end
  end
end
```

**Comment by edusantana** [comment]
It would be nice to have a [generator for this migration](http://guides.rubyonrails.org/generators.html).

**Comment by mainRomainRo** [comment]
Hi ! Does this gem works with the User generated from the Devise gem ? I can't do it

**Comment by johnvuko** [comment]
This is not related to Devise, Devise is for authentication, this gem only simplify the usage of address.
Addresses can be used for other things than users, places, companies for example...
If you want to add an address to the User model juste create a migration like this:

```
class AddAddressToUsers < ActiveRecord::Migration[5.2]
  def change
    change_table :users do |t|
      t.address :address
    end
  end
end
```

and add to your User model `has_address :address`.
